server:
  port: 8989
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /**
    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


swagger:
  enable: true